In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Users\LENOVO\Desktop\datasets\6. India Census 2011.csv")
df

,District_code,State_name,District_name,Population,Male,Female,Literate,Workers,Male_Workers,Female_Workers,...,Christians,Sikhs,Buddhists,Jains,Secondary_Education,Higher_Education,Graduate_Education,Age_Group_0_29,Age_Group_30_49,Age_Group_50
0,1,JAMMU AND KASHMIR,Kupwara,870354,474190,396164,439654,229064,190899,38165,...,1700,5600,66,39,74948,39709,21751,600759,178435,89679
1,2,JAMMU AND KASHMIR,Badgam,753745,398041,355704,335649,214866,162578,52288,...,1489,5559,47,6,66459,41367,27950,503223,160933,88978
2,3,JAMMU AND KASHMIR,Leh(Ladakh),133487,78971,54516,93770,75079,53265,21814,...,658,1092,88635,103,16265,8923,6197,70703,41515,21019
3,4,JAMMU AND KASHMIR,Kargil,140802,77785,63017,86236,51873,39839,12034,...,604,1171,20126,28,16938,9826,3077,87532,35561,17488
4,5,JAMMU AND KASHMIR,Punch,476835,251899,224936,261724,161393,117677,43716,...,958,11188,83,10,46062,29517,13962,304979,109818,61334
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
635,636,PONDICHERRY,Mahe,41816,19143,22673,36470,11802,9093,2709,...,958,3,21,14,8773,5711,4475,19760,12543,9428
636,637,PONDICHERRY,Karaikal,200222,97809,102413,154916,68301,53139,15162,...,18391,46,63,54,29456,15930,18998,102333,60089,37434
637,638,ANDAMAN AND NICOBAR ISLANDS,Nicobars,36842,20727,16115,25332,17125,12714,4411,...,26077,343,119,0,6325,3668,1300,18786,12088,5922
638,639,ANDAMAN AND NICOBAR ISLANDS,North AND Middle Andaman,105597,54861,50736,78683,38579,30612,7967,...,21870,77,84,4,12707,10042,5133,57350,30741,17464
639,640,ANDAMAN AND NICOBAR ISLANDS,South Andaman,238142,127283,110859,190266,96831,77563,19268,...,33037,866,135,27,42150,29910,22388,128402,76332,33128

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 640 entries, 0 to 639
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   District_code         640 non-null    int64
 1   State_name            640 non-null    object
 2   District_name         640 non-null    object
 3   Population            640 non-null    int64
 4   Male                  640 non-null    int64
 5   Female                640 non-null    int64
 6   Literate              640 non-null    int64
 7   Workers               640 non-null    int64
 8   Male_Workers          640 non-null    int64
 9   Female_Workers        640 non-null    int64
 10  Cultivator_Workers    640 non-null    int64
 11  Agricultural_Workers  640 non-null    int64
 12  Household_Workers     640 non-null    int64
 13  Hindus                640 non-null    int64
 14  Muslims               640 non-null    int64
 15  Christians            640 non-null    int64
 16  Sikhs                 640 non-null    int64
 17  Buddhists             640 non-null    int64
 18  Jains                 640 non-null    int64
 19  Secondary_Education   640 non-null    int64
 20  Higher_Education      640 non-null    int64
 21  Graduate_Education    640 non-null    int64
 22  Age_Group_0_29        640 non-null    int64
 23  Age_Group_30_49       640 non-null    int64
 24  Age_Group_50          640 non-null    int64
dtypes: int64(23), object(2)
memory usage: 125.1+ KB

In [3]:
df.isnull().sum()

District_code           0
State_name              0
District_name           0
Population              0
Male                    0
Female                  0
Literate                0
Workers                 0
Male_Workers            0
Female_Workers          0
Cultivator_Workers      0
Agricultural_Workers    0
Household_Workers       0
Hindus                  0
Muslims                 0
Christians              0
Sikhs                   0
Buddhists               0
Jains                   0
Secondary_Education     0
Higher_Education        0
Graduate_Education      0
Age_Group_0_29          0
Age_Group_30_49         0
Age_Group_50            0
dtype: int64

<h3>How will you hide the indexes of the dataframe</h3>

In [4]:
df.head(2)

,District_code,State_name,District_name,Population,Male,Female,Literate,Workers,Male_Workers,Female_Workers,...,Christians,Sikhs,Buddhists,Jains,Secondary_Education,Higher_Education,Graduate_Education,Age_Group_0_29,Age_Group_30_49,Age_Group_50
0,1,JAMMU AND KASHMIR,Kupwara,870354,474190,396164,439654,229064,190899,38165,...,1700,5600,66,39,74948,39709,21751,600759,178435,89679
1,2,JAMMU AND KASHMIR,Badgam,753745,398041,355704,335649,214866,162578,52288,...,1489,5559,47,6,66459,41367,27950,503223,160933,88978

In [12]:
df.head().style.hide(axis = 'index')   #df.style.hide(axis = 'index')   ya columns bhi likh sakte toh sirf index bachega baaki saare columns hide ho jayenge

<h3>How can we set the caption/heading on the dataframe.</h3>

In [16]:
df.head().style.set_caption("India Census 2011 Dataset")

<h3>Show the records related with the districts - New Delhi, lucknow , jaipur</h3>

In [17]:
df[df['District_name'].isin(['New Delhi' , 'Lucknow', 'Jaipur'])]

,District_code,State_name,District_name,Population,Male,Female,Literate,Workers,Male_Workers,Female_Workers,...,Christians,Sikhs,Buddhists,Jains,Secondary_Education,Higher_Education,Graduate_Education,Age_Group_0_29,Age_Group_30_49,Age_Group_50
93,94,NCT OF DELHI,New Delhi,142004,77942,64062,114179,59541,46940,12601,...,4852,2933,312,679,15942,17742,23934,76076,43913,21773
109,110,RAJASTHAN,Jaipur,6626178,3468507,3157671,4300965,2464893,1714947,749946,...,12708,18782,1020,81079,659389,455527,703673,4091148,1646480,884057
156,157,UTTAR PRADESH,Lucknow,4589838,2394476,2195362,3127260,1542806,1226399,316407,...,20493,23883,3877,4975,428121,378742,639260,2678289,1161686,685258

<h3>Calculate state wise <br>
1. Total number of population<br>
2. total no of population with different religions.</h3>

In [19]:
df.groupby('State_name').Population.sum().sort_values(ascending = False)

State_name
UTTAR PRADESH                  199812341
MAHARASHTRA                    112374333
BIHAR                          104099452
WEST BENGAL                     91276115
ANDHRA PRADESH                  84580777
MADHYA PRADESH                  72626809
TAMIL NADU                      72147030
RAJASTHAN                       68548437
KARNATAKA                       61095297
GUJARAT                         60439692
ORISSA                          41974218
KERALA                          33406061
JHARKHAND                       32988134
ASSAM                           31205576
PUNJAB                          27743338
CHHATTISGARH                    25545198
HARYANA                         25351462
NCT OF DELHI                    16787941
JAMMU AND KASHMIR               12541302
UTTARAKHAND                     10086292
HIMACHAL PRADESH                 6864602
TRIPURA                          3673917
MEGHALAYA                        2966889
MANIPUR                          2855794
NAGALAND                         1978502
GOA                              1458545
ARUNACHAL PRADESH                1383727
PONDICHERRY                      1247953
MIZORAM                          1097206
CHANDIGARH                       1055450
SIKKIM                            610577
ANDAMAN AND NICOBAR ISLANDS       380581
DADRA AND NAGAR HAVELI            343709
DAMAN AND DIU                     243247
LAKSHADWEEP                        64473
Name: Population, dtype: int64

In [20]:
df.columns

Index(['District_code', 'State_name', 'District_name', 'Population', 'Male',
       'Female', 'Literate', 'Workers', 'Male_Workers', 'Female_Workers',
       'Cultivator_Workers', 'Agricultural_Workers', 'Household_Workers',
       'Hindus', 'Muslims', 'Christians', 'Sikhs', 'Buddhists', 'Jains',
       'Secondary_Education', 'Higher_Education', 'Graduate_Education',
       'Age_Group_0_29', 'Age_Group_30_49', 'Age_Group_50'],
      dtype='object')

In [24]:
df.groupby('State_name')[['Hindus', 'Muslims', 'Christians', 'Sikhs', 'Buddhists', 'Jains']].sum().sort_values(by = 'Sikhs' , ascending = False)

,Hindus,Muslims,Christians,Sikhs,Buddhists,Jains
State_name,,,,,,
PUNJAB,10678138,535489,348230,16004754,33237,45040
HARYANA,22171128,1781342,50353,1243752,7514,52613
RAJASTHAN,60657103,6215377,96430,872930,12185,622023
UTTAR PRADESH,159312654,38483967,356448,643500,206285,213267
NCT OF DELHI,13712100,2158684,146093,570581,18449,166231
UTTARAKHAND,8368636,1406825,37781,236340,14926,9183
JAMMU AND KASHMIR,3566674,8567485,35631,234848,112584,2490
MAHARASHTRA,89703057,12971152,1080073,223247,6531200,1400349
MADHYA PRADESH,66007121,4774695,213282,151412,216052,567028
CHANDIGARH,852574,51447,8720,138329,1160,1960
HIMACHAL PRADESH,6532765,149881,12646,79896,78659,1805
JHARKHAND,22376051,4793994,1418608,71422,8956,14974
CHHATTISGARH,23819789,514998,490542,70036,70467,61510
WEST BENGAL,64385546,24654825,658618,63523,282898,60141
GUJARAT,53533988,5846761,316178,58246,30483,579654
ANDHRA PRADESH,74824149,8082412,1129784,40244,36692,53849
KARNATAKA,51317472,7893065,1142647,28773,95710,440280
BIHAR,86078686,17557809,129247,23779,25453,18914
ORISSA,39300341,911670,1161708,21991,13852,9420
ASSAM,19180759,10679345,1165867,20672,54993,25949
TAMIL NADU,63188168,4229479,4418331,14601,11186,89265
KERALA,18282492,8873472,6141269,3814,4752,4489
ARUNACHAL PRADESH,401876,27045,418732,3287,162815,771
MEGHALAYA,342078,130399,2213027,3045,9864,627
NAGALAND,173054,48963,1739651,1890,6759,2655
SIKKIM,352662,9867,60522,1868,167216,314
MANIPUR,1181876,239836,1179043,1527,7084,1692
GOA,963877,121564,366130,1473,1095,1109
ANDAMAN AND NICOBAR ISLANDS,264296,32413,80984,1286,338,31
TRIPURA,3063903,316042,159882,1070,125385,860
PONDICHERRY,1089409,75556,78550,297,451,1400
MIZORAM,30136,14832,956331,286,93411,376
DADRA AND NAGAR HAVELI,322857,12922,5113,217,634,1186
DAMAN AND DIU,220150,19277,2820,172,217,287
LAKSHADWEEP,1788,62268,317,8,10,11

<h3>how many male workers were there in Maharashtra state?</h3>

In [2]:
df.head(2)

,District_code,State_name,District_name,Population,Male,Female,Literate,Workers,Male_Workers,Female_Workers,...,Christians,Sikhs,Buddhists,Jains,Secondary_Education,Higher_Education,Graduate_Education,Age_Group_0_29,Age_Group_30_49,Age_Group_50
0,1,JAMMU AND KASHMIR,Kupwara,870354,474190,396164,439654,229064,190899,38165,...,1700,5600,66,39,74948,39709,21751,600759,178435,89679
1,2,JAMMU AND KASHMIR,Badgam,753745,398041,355704,335649,214866,162578,52288,...,1489,5559,47,6,66459,41367,27950,503223,160933,88978

In [9]:
df[df['State_name'] == 'MAHARASHTRA']['Male_Workers'].sum()

np.int64(32616875)

<h3>How to set a column as index of the dataframe</h3>

In [10]:
df.head()

,District_code,State_name,District_name,Population,Male,Female,Literate,Workers,Male_Workers,Female_Workers,...,Christians,Sikhs,Buddhists,Jains,Secondary_Education,Higher_Education,Graduate_Education,Age_Group_0_29,Age_Group_30_49,Age_Group_50
0,1,JAMMU AND KASHMIR,Kupwara,870354,474190,396164,439654,229064,190899,38165,...,1700,5600,66,39,74948,39709,21751,600759,178435,89679
1,2,JAMMU AND KASHMIR,Badgam,753745,398041,355704,335649,214866,162578,52288,...,1489,5559,47,6,66459,41367,27950,503223,160933,88978
2,3,JAMMU AND KASHMIR,Leh(Ladakh),133487,78971,54516,93770,75079,53265,21814,...,658,1092,88635,103,16265,8923,6197,70703,41515,21019
3,4,JAMMU AND KASHMIR,Kargil,140802,77785,63017,86236,51873,39839,12034,...,604,1171,20126,28,16938,9826,3077,87532,35561,17488
4,5,JAMMU AND KASHMIR,Punch,476835,251899,224936,261724,161393,117677,43716,...,958,11188,83,10,46062,29517,13962,304979,109818,61334

In [11]:
df.set_index('District_code')

,State_name,District_name,Population,Male,Female,Literate,Workers,Male_Workers,Female_Workers,Cultivator_Workers,...,Christians,Sikhs,Buddhists,Jains,Secondary_Education,Higher_Education,Graduate_Education,Age_Group_0_29,Age_Group_30_49,Age_Group_50
District_code,,,,,,,,,,,,,,,,,,,,,
1,JAMMU AND KASHMIR,Kupwara,870354,474190,396164,439654,229064,190899,38165,34680,...,1700,5600,66,39,74948,39709,21751,600759,178435,89679
2,JAMMU AND KASHMIR,Badgam,753745,398041,355704,335649,214866,162578,52288,55299,...,1489,5559,47,6,66459,41367,27950,503223,160933,88978
3,JAMMU AND KASHMIR,Leh(Ladakh),133487,78971,54516,93770,75079,53265,21814,20869,...,658,1092,88635,103,16265,8923,6197,70703,41515,21019
4,JAMMU AND KASHMIR,Kargil,140802,77785,63017,86236,51873,39839,12034,8266,...,604,1171,20126,28,16938,9826,3077,87532,35561,17488
5,JAMMU AND KASHMIR,Punch,476835,251899,224936,261724,161393,117677,43716,54264,...,958,11188,83,10,46062,29517,13962,304979,109818,61334
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
636,PONDICHERRY,Mahe,41816,19143,22673,36470,11802,9093,2709,43,...,958,3,21,14,8773,5711,4475,19760,12543,9428
637,PONDICHERRY,Karaikal,200222,97809,102413,154916,68301,53139,15162,2372,...,18391,46,63,54,29456,15930,18998,102333,60089,37434
638,ANDAMAN AND NICOBAR ISLANDS,Nicobars,36842,20727,16115,25332,17125,12714,4411,322,...,26077,343,119,0,6325,3668,1300,18786,12088,5922
639,ANDAMAN AND NICOBAR ISLANDS,North AND Middle Andaman,105597,54861,50736,78683,38579,30612,7967,10727,...,21870,77,84,4,12707,10042,5133,57350,30741,17464
640,ANDAMAN AND NICOBAR ISLANDS,South Andaman,238142,127283,110859,190266,96831,77563,19268,5518,...,33037,866,135,27,42150,29910,22388,128402,76332,33128

<h3>Add a suffix to the column names.<br>
Add a prefix to the column names.</h3>

In [14]:
df.add_suffix("_willBeOnBack")

,District_code_willBeOnBack,State_name_willBeOnBack,District_name_willBeOnBack,Population_willBeOnBack,Male_willBeOnBack,Female_willBeOnBack,Literate_willBeOnBack,Workers_willBeOnBack,Male_Workers_willBeOnBack,Female_Workers_willBeOnBack,...,Christians_willBeOnBack,Sikhs_willBeOnBack,Buddhists_willBeOnBack,Jains_willBeOnBack,Secondary_Education_willBeOnBack,Higher_Education_willBeOnBack,Graduate_Education_willBeOnBack,Age_Group_0_29_willBeOnBack,Age_Group_30_49_willBeOnBack,Age_Group_50_willBeOnBack
0,1,JAMMU AND KASHMIR,Kupwara,870354,474190,396164,439654,229064,190899,38165,...,1700,5600,66,39,74948,39709,21751,600759,178435,89679
1,2,JAMMU AND KASHMIR,Badgam,753745,398041,355704,335649,214866,162578,52288,...,1489,5559,47,6,66459,41367,27950,503223,160933,88978
2,3,JAMMU AND KASHMIR,Leh(Ladakh),133487,78971,54516,93770,75079,53265,21814,...,658,1092,88635,103,16265,8923,6197,70703,41515,21019
3,4,JAMMU AND KASHMIR,Kargil,140802,77785,63017,86236,51873,39839,12034,...,604,1171,20126,28,16938,9826,3077,87532,35561,17488
4,5,JAMMU AND KASHMIR,Punch,476835,251899,224936,261724,161393,117677,43716,...,958,11188,83,10,46062,29517,13962,304979,109818,61334
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
635,636,PONDICHERRY,Mahe,41816,19143,22673,36470,11802,9093,2709,...,958,3,21,14,8773,5711,4475,19760,12543,9428
636,637,PONDICHERRY,Karaikal,200222,97809,102413,154916,68301,53139,15162,...,18391,46,63,54,29456,15930,18998,102333,60089,37434
637,638,ANDAMAN AND NICOBAR ISLANDS,Nicobars,36842,20727,16115,25332,17125,12714,4411,...,26077,343,119,0,6325,3668,1300,18786,12088,5922
638,639,ANDAMAN AND NICOBAR ISLANDS,North AND Middle Andaman,105597,54861,50736,78683,38579,30612,7967,...,21870,77,84,4,12707,10042,5133,57350,30741,17464
639,640,ANDAMAN AND NICOBAR ISLANDS,South Andaman,238142,127283,110859,190266,96831,77563,19268,...,33037,866,135,27,42150,29910,22388,128402,76332,33128

In [15]:
df.add_prefix("willBeOnFront_")

,willBeOnFront_District_code,willBeOnFront_State_name,willBeOnFront_District_name,willBeOnFront_Population,willBeOnFront_Male,willBeOnFront_Female,willBeOnFront_Literate,willBeOnFront_Workers,willBeOnFront_Male_Workers,willBeOnFront_Female_Workers,...,willBeOnFront_Christians,willBeOnFront_Sikhs,willBeOnFront_Buddhists,willBeOnFront_Jains,willBeOnFront_Secondary_Education,willBeOnFront_Higher_Education,willBeOnFront_Graduate_Education,willBeOnFront_Age_Group_0_29,willBeOnFront_Age_Group_30_49,willBeOnFront_Age_Group_50
0,1,JAMMU AND KASHMIR,Kupwara,870354,474190,396164,439654,229064,190899,38165,...,1700,5600,66,39,74948,39709,21751,600759,178435,89679
1,2,JAMMU AND KASHMIR,Badgam,753745,398041,355704,335649,214866,162578,52288,...,1489,5559,47,6,66459,41367,27950,503223,160933,88978
2,3,JAMMU AND KASHMIR,Leh(Ladakh),133487,78971,54516,93770,75079,53265,21814,...,658,1092,88635,103,16265,8923,6197,70703,41515,21019
3,4,JAMMU AND KASHMIR,Kargil,140802,77785,63017,86236,51873,39839,12034,...,604,1171,20126,28,16938,9826,3077,87532,35561,17488
4,5,JAMMU AND KASHMIR,Punch,476835,251899,224936,261724,161393,117677,43716,...,958,11188,83,10,46062,29517,13962,304979,109818,61334
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
635,636,PONDICHERRY,Mahe,41816,19143,22673,36470,11802,9093,2709,...,958,3,21,14,8773,5711,4475,19760,12543,9428
636,637,PONDICHERRY,Karaikal,200222,97809,102413,154916,68301,53139,15162,...,18391,46,63,54,29456,15930,18998,102333,60089,37434
637,638,ANDAMAN AND NICOBAR ISLANDS,Nicobars,36842,20727,16115,25332,17125,12714,4411,...,26077,343,119,0,6325,3668,1300,18786,12088,5922
638,639,ANDAMAN AND NICOBAR ISLANDS,North AND Middle Andaman,105597,54861,50736,78683,38579,30612,7967,...,21870,77,84,4,12707,10042,5133,57350,30741,17464
639,640,ANDAMAN AND NICOBAR ISLANDS,South Andaman,238142,127283,110859,190266,96831,77563,19268,...,33037,866,135,27,42150,29910,22388,128402,76332,33128